### ISSUE TITLE
打包下载经常报错400，可以修改成遍历下载单文件吗

### ISSUE THREAD

**Issue by 2545504198** [Bao-qing/123pan#3]
RT

**Comment by Bao-qing** [comment]
em，可以添加相关功能

**Comment by Bao-qing** [comment]
我这边好像并没有出现报错400

**Comment by 2545504198** [comment]
报错如下，好像是获取不到压缩包的下载链接，有可能是压缩包比较大？但是小文件打包也会有400，偶尔也能打包下载
![image](https://github.com/user-attachments/assets/95dc6df2-e5e6-43d4-8a34-38b158123897)

**Comment by 2545504198** [comment]
android.py也是一样的报错，都试过
