### ISSUE TITLE
打开以后 windows 控制台有乱码 

### ISSUE THREAD

**Issue by zhanglong1124** [Bao-qing/123pan#4]
![Snipaste_2024-09-27_11-39-53](https://github.com/user-attachments/assets/aea0d75c-5678-4707-9a0a-0f276e5d7d0b)

**Comment by Bao-qing** [comment]
原来大家用的都是旧终端啊

**Comment by Bao-qing** [comment]
将在下一个发行版修复

**Comment by Bao-qing** [comment]
顺便问一下，进度条是不是也有问题

**Comment by zhanglong1124** [comment]
![image](https://github.com/user-attachments/assets/0ee0535a-1cb0-48e5-aba9-7a43ba938704)
进度条倒是没有乱码

**Comment by Bao-qing** [comment]
最新版已发布，修复此问题。
