### ISSUE TITLE
研究一下alist挂载123pan的走安卓客户端协议呗

### ISSUE THREAD

**Issue by ShelbyAlan** [Bao-qing/123pan#5]

**Comment by Three-taile-dragon** [comment]
可参考这个分支，自行构建 https://github.com/loognsss/blist/tree/123
> 仅修改了 `123云盘` 驱动 和`123云盘分享`驱动
> 后续计划 添加 `TV端` 扫码登录功能

**Comment by Bao-qing** [comment]
不是很懂go
